In [1]:
A= [1,2,3,4,5,6]
A.extend([13,21,34])
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [2]:
import numpy as  np
idMat = np.eye(3)
print(idMat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
import pandas as pd
data_set = pd.read_csv('http://bit.ly/HDSC-Dataset')
data_set

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [5]:
data_set.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].count()

fuel_type_code_pudl
coal        8547
gas        11486
nuclear      818
oil         8064
other        167
waste        441
Name: fuel_cost_per_unit_burned, dtype: int64

In [6]:
data_set.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [8]:
pd.DataFrame(data_set.skew(),columns =['skewness'])

skewness
utility_id_ferc1                0.605070
report_year                     0.006953
fuel_qty_burned                15.851495
fuel_mmbtu_per_unit             4.135217
fuel_cost_per_unit_burned      19.787440
fuel_cost_per_unit_delivered  105.014227
fuel_cost_per_mmbtu           171.675535

In [9]:
pd.DataFrame(data_set.kurt(),columns =['kurtosis'])

kurtosis
utility_id_ferc1                  1.088432
report_year                      -1.145656
fuel_qty_burned                 651.369450
fuel_mmbtu_per_unit              55.595695
fuel_cost_per_unit_burned       485.255851
fuel_cost_per_unit_delivered  11765.054226
fuel_cost_per_mmbtu           29489.132594

In [10]:
data_set.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [11]:
data_set.groupby('fuel_unit')['fuel_unit'].count().describe().mean()

3462.3679931459947

In [12]:
data_set[data_set.fuel_type_code_pudl=='coal'].describe()

utility_id_ferc1  report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count       8547.000000  8547.000000     8.547000e+03          8547.000000   
mean         115.637534  2004.623143     1.903473e+06            20.762780   
std           72.859332     7.137389     7.206434e+06             3.557467   
min            1.000000  1994.000000     3.000000e+00            10.168000   
25%           51.000000  1998.000000     4.599130e+05            17.408000   
50%          122.000000  2004.000000     1.018766e+06            21.250000   
75%          174.000000  2011.000000     2.104158e+06            24.141000   
max          514.000000  2018.000000     5.558942e+08            28.926390   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count                8547.000000                   8547.000000   
mean                   67.421830                    116.951141   
std                   943.771433                   4043.732781   
min                     0.000000                    -40.725000   
25%                    23.958500                     21.740000   
50%                    33.318000                     31.407000   
75%                    44.668000                     43.380500   
max                 44033.320000                 270604.000000   

       fuel_cost_per_mmbtu  
count          8547.000000  
mean              1.787190  
std               0.802419  
min               0.500000  
25%               1.210000  
50%               1.586000  
75%               2.163000  
max               6.895000

In [13]:
data_set.groupby(['report_year'])['fuel_cost_per_unit_delivered'].sum()

report_year
1994    7.859053e+04
1995    3.931506e+04
1996    1.000602e+07
1997    1.218738e+07
1998    3.178799e+05
1999    2.682921e+04
2000    1.352903e+06
2001    8.142834e+04
2002    5.735121e+04
2003    6.740849e+04
2004    1.663129e+05
2005    5.258506e+04
2006    4.805125e+04
2007    5.476283e+04
2008    7.194631e+04
2009    7.975923e+05
2010    1.158381e+05
2011    7.412059e+04
2012    7.581617e+04
2013    2.065968e+05
2014    2.256952e+05
2015    3.569033e+05
2016    1.074344e+05
2017    4.587348e+04
2018    4.748057e+05
Name: fuel_cost_per_unit_delivered, dtype: float64